language: python

python:
  - "2.7"
  - "3.6"

script:
  - touch test
deploy:
  provider: pypi
  user: billfordx
  password:
    secure: nlIyW5YNVMrQfhDGxS44Ay7TBch3V1EwgvDgHh71LnvxGntUCbaNeTFHUGEcqEk1NHye/RBRLEj7PmZ0sCBe8lNL1OkxbdT2ek72ZtWFZB5gzKi58v67cf2ECuGb5TVW6WLkqrs58IrVsMBdfOn4iiSMNJ/rSfrJ9L1YSmIUmjWmyJvQqeHX1H9bBK8zJwpmFj2P9iCSeDtuJdvbEizXgOd1DzH51Qkpe+V3kbIianl/ox6EI1aYK0kEMrwbAMNtxy5M7UaUKWxNGpNZeGAgtvXKndOw8UdItsYN4bHUCFhKKDgrA9QhIbtwy+Pljay3ogtePxSjCzivw2fW4LYFlCXQIvd7KejwdTDBHsF2gbHCpTbH96TvKqUUows9UH0EsNdmRHVzoMDLZ99e1t5VUVSzKDlu/ahfOP/JgY7zv7VgDQH24sfssxyhy1YtNfa/A7THNyCLLjIyY+e4VmMeFFmcYsL4jFgYKmZkOQqrG3pKuVzer84/WpDatrdz5mHozHHsxbPKXScagPHDztVYRVuCBBVG+CLZUeHA41iLnU627C9h+KM7CqK9mPc9aZNHuWxegciVJGE5mHaVV4q1aOvSlaMQVDH1I6tcXeJ+ghRfTFC5yhIo1QJWAJffFP5iFwDuscZML9ES6GhysQNeSnt91LDu1Qm200eJF7ZMoYs=
  on:
    tags: true
    branch: master
